//{{NO_DEPENDENCIES}}
// Включаемый файл, созданный в Microsoft Visual C++.
// Используется FreePcb.rc
//
#define ID_GO                           3
#define IDCANCEL2                       3
#define ID_SAVE_AND_IMPORT              3
#define ID_Q1                           3
#define ID_Q2                           4
#define ID_Q3                           5
#define SH_X                            20
#define SH_X_TAB                        55
#define IDD_ABOUTBOX                    100
#define IDR_HTML_DLGPARTLIST            103
#define IDR_HTML_CDlgSetAreaHatch       104
#define IDR_HTML_DLGAREALAYER           105
#define ID_ALIGN_PARTS                  126
#define ID_APPROXIMATION_ARC            127
#define IDR_MAINFRAME                   128
#define IDR_FREEPCTYPE                  129
#define IDD_ADD_PART                    130
#define ID_ADD_PART                     131
#define ID_ADD_NET                      132
#define ID_ADD_AREA                     133
#define ID_ADD_CONNECTION               134
#define IDD_ADD_NET                     135
#define ID_SELECT_SIMILAR_P             136
#define ID_SELECT_SIMILAR               137
#define ID_ADD_VIAS_GRID                138
#define ID_REMOVEMERGE                  139
#define ID_FILE_DUMP                    140
#define IDD_ASSIGN_NET                  141
#define IDD_SEGMENT_WIDTH               142
#define IDD_EDIT_BOARD_CORNER           143
#define IDR_CONTEXT                     144
#define ID_PART_GLUE                    145
#define ID_PART_UNGLUE                  146
#define ID_PART_MOVE                    147
#define ID_PART_OPTIMIZE                148
#define ID_PART_REPLACE                 149
#define ID_PART_DELETE                  150
#define ID_PART_PROPERTIES              151
#define ID_PAD_ADDTONET                 152
#define ID_PAD_DETACHFROMNET            153
#define ID_PAD_OPTIMIZERATLINES         154
#define ID_PAD_PROPERTIES               155
#define ID_SEGMENT_UNROUTE              156
#define ID_SEGMENT_PROPERTIES           157
#define ID_RATLINE_ROUTE                158
#define ID_RATLINE_OPTIMIZE             159
#define ID_RATLINE_PROPERTIES           160
#define ID_SEGMENT_LOCKCONNECTION       161
#define ID_RATLINE_LOCKCONNECTION       162
#define ID_NONE_ADDPART                 163
#define ID_NONE_ADDTEXT                 164
#define ID_GROUP_SAVETODXF              165
#define ID_NONE_ADDBOARDOUTLINE         166
#define ID_NONE_ADDCOPPERAREA           167
#define ID_TEXT_MOVE                    168
#define ID_TEXT_EDIT                    169
#define ID_TEXT_DELETE                  170
#define ID_TEXT_PROPERTIES              171
#define ID_VERTEX_MOVE                  172
#define ID_VERTEX_DELETE                173
#define ID_VERTEX_PROPERITES            174
#define ID_LINE_MOVE                    175
#define ID_LINE_DELETE                  176
#define ID_LINE_PROPERTIES              177
#define ID_AREACORNER_MOVE              178
#define ID_AREACORNER_DELETE            179
#define ID_AREACORNER_PROPERTIES        180
#define ID_AREAEDGE_ADDCORNER           181
#define ID_AREAEDGE_DELETE              182
#define ID_AREAEDGE_PROPERTIES          183
#define ID_AREACORNER_DELETEAREA        184
#define ID_REF_MOVE                     185
#define ID_REF_PROPERTIES               186
#define ID_Menu                         187
#define ID_PARTNAME_MOVE                188
#define ID_PARTNAME_PROPERTIES          189
#define IDD_ADD_TEXT                    190
#define ID_PAD_CONNECTTOPIN             191
#define ID_SEGMENT_SETWIDTH             192
#define ID_RATLINE_UNLOCKCONNECTION     193
#define ID_RATLINE_COMPLETE             194
#define ID_RATLINE_SETWIDTH             195
#define ID_RATLINE_DELETECONNECTION     196
#define IDD_NET_LIST                    197
#define ID_VIEW_NETLIST                 198
#define IDD_EDIT_NET                    199
#define ID_NONE_NOSELECTION             200
#define ID_ADD_OP                       201
#define ID_OP_CORNER_MOVE               202
#define ID_ADD_SYMMETRICAL_BLANK        203
#define ID_OP_CORNER_EDIT               204
#define ID_OP_SIDE_ADDCORNER            205
#define ID_OP_SIDE_INSERTCORNER         205
#define ID_OP_SIDE_DELETEOUTLINE        206
#define ID_OP_CORNER_DELETEOUTLINE      207
#define ID_OP_CORNER_DELETECORNER       210
#define ID_OP_CORNER_DELETEOUTLINE211   211
#define ID_OP_SIDE_ADDCORNER212         212
#define ID_OP_SIDE_DELETEOUTLINE213     213
#define ID_PAD_STARTSTUBTRACE           215
#define ID_SEGMENT_DELETE               216
#define ID_ENDVERTEX_MOVE               217
#define ID_ENDVERTEX_ADDSEGMENTS        218
#define ID_ENDVERTEX_DELETE             219
#define ID_ENDVERTEX_EDIT               220
#define ID_ENDVERTEX_ADDCONNECTION      221
#define IDI_ICON1                       222
#define IDI_ICON2                       223
#define IDD_ADD_AREA                    224
#define ID_ENDVERTEX_ADDVIA             225
#define ID_ENDVERTEX_REMOVEVIA          226
#define IDD_PROJECT_OPTIONS             227
#define IDD_ADD_WIDTH_MENU_ITEM         228
#define IDR_MYTOOLBAR                   229
#define ID_FILE_CLOSE231                231
#define IDD_SET_TRACE_WIDTHS            232
#define IDD_LAYERS                      235
#define ID_VIEW_LAYERS                  236
#define ID_ADD_TEXT                     237
#define IDD_PARTLIST                    238
#define ID_VIEW_PARTLIST                239
#define ID_SEGMENT_DELETETRACE          241
#define IDD_REF_TEXT                    242
#define ID_FOOTPRINT_FILE_IMPORT        244
#define IDD_DIALOG1                     247
#define IDD_TEST                        247
#define IDD_IMPORT                      247
#define ID_VIEW_PCB_EDITOR              248
#define IDR_FOOTPRINT                   249
#define ID_ADD_PIN                      249
#define ID_FILE_CONVERT                 250
#define IDR_FP_CONTEXT                  250
#define ID_CONVERT                      251
#define IDR_MAINFRAME_DRAG              251
#define IDD_IVEX_DIALOG                 252
#define IDR_FOOTPRINT_DRAG              252
#define IDC_EDIT_INFILE                 253
#define IDC_BUTTON_INFILE               254
#define IDC_EDIT_OUTFILE                255
#define IDC_BUTTON_OUTFILE              256
#define ID_FILE_CONVERT257              257
#define ID_OP_SIDE_CONVERTTOSTRAIGHTLINE 258
#define ID_OP_SIDE_CONVERTTOARC_CW      259
#define ID_OP_SIDE_CONVERTTOARC_CCW     260
#define ID_SEGMENT_UNROUTETRACE         261
#define ID_VERTEX_UNROUTETRACE          262
#define IDD_DIALOG2                     263
#define IDD_INDEXING                    264
#define IDD_CAD                         265
#define ID_FILE_GENERATECADFILES        266
#define IDD_LOG                         267
#define ID_VIEW_ENTIREBOARD             268
#define ID_VIEW_ALLELEMENTS             269
#define ID_VIEW_LAYERS270               270
#define IDD_WIZ_QUAD                    271
#define IDB_BITMAP_QUAD                 272
#define ID_TOOLS                        273
#define ID_TOOLS_FOOTPRINTWIZARD        274
#define IDB_BITMAP_DIP                  277
#define ID_FILE_GENERATEDXFFILE1        278
#define ID_FILE_GENERATEDXFFILE2        279
#define ID_FILE_GENERATEDXFFILE3        280
#define ID_FILE_GENERATEDXFFILE4        281
#define ID_FILE_GENERATEDXFFILE5        282
#define ID_FILE_GENERATEDXFFILE6        283
#define ID_FILE_GENERATEDXFFILE7        284
#define ID_FILE_GENERATEDXFFILE8        285
#define ID_FILE_GENERATEGRBLFILE1       286
#define ID_FILE_GENERATEGRBLFILE2       287
#define ID_FILE_GENERATEGRBLFILE3       288
#define ID_FILE_GENERATEGRBLFILE4       289
#define ID_FILE_GENERATEGRBLFILE5       290
#define ID_FILE_GENERATEGRBLFILE6       291
#define IDB_BITMAP_SIP                  292
#define ID_FILE_GENERATEGRBLFILE7       292
#define IDD_SAVE_FOOTPRINT              293
#define ID_FILE_GENERATEGRBLFILE8       293
#define ID_Menu287                      294
#define ID_FILE_GENERATEGRBLFILE9       294
#define ID_VIEW_VIEWPCB                 295
#define ID_FILE_GENERATEGRBLFILE10      295
#define IDD_ADD_PIN                     296
#define ID_FILE_GENERATEGRBLFILE11      296
#define ID_TOOLS_FOOTPRINTEDITOR        297
#define ID_FILE_GENERATEGRBLFILE12      297
#define ID_FOOTPRINT_FILE_REPLACE_IN_PROJECT 298
#define ID_FILE_GENERATEGRBLFILE13      298
#define ID_FOOTPRINT_FILE_SAVE_AS       299
#define ID_FOOTPRINT_FILE_CLOSE         300
#define ID_FOOTPRINT_FILE_NEW           301
#define IDD_ADD_POLY                    302
#define IDD_IMPORT_FOOTPRINT            303
#define ID_FILE_OPENFOOTPRINTEDITOR     304
#define ID_Menu298                      305
#define ID_AREAEDGE_HATCHSTYLE          306
#define IDD_DIALOG3                     307
#define IDD_SET_AREA_HATCH              308
#define ID_PROJECT_OPTIONS              309
#define IDD_FP_REF_TEXT                 310
#define ID_PART_EDITFOOTPRINT           311
#define ID_PROTECTION                   312
#define ID_VIEW_ENTIREFOOTPRINT         313
#define IDB_BITMAP_HDR1                 314
#define IDB_BITMAP_HDR2                 315
#define IDD_LIB_MANAGER                 316
#define IDD_DUP_FP_NAME                 317
#define IDB_BITMAP_BGA                  318
#define IDD_DRC                         319
#define IDD_SHOW_PART                   320
#define IDD_CROP                        321
#define IDD_EXPORT                      322
#define IDB_BITMAP_EDGE                 323
#define IDB_BITMAP_EDGE2                324
#define IDD_IMPORT_OPTIONS              325
#define IDD_ADD_MASK_CUTOUT             326
#define IDD_CHANGE_LAYER                327
#define IDD_MOVE_ORIGIN                 328
#define IDD_SHORTCUTS                   329
#define IDD_MY_MESSAGE                  330
#define IDD_VIA                         331
#define IDD_ADD_SYMMETRICAL_BLANK       332
#define IDD_AREA_LAYER                  333
#define IDD_MY_MESSAGE2                 334
#define IDD_GROUP_PASTE                 335
#define IDD_REASSIGN_LAYERS             336
#define IDD_EXPORT_DSN                  337
#define IDD_IMPORT_SES                  338
#define IDD_SIDE_STYLE                  339
#define IDD_REPORT                      340
#define IDD_CENTROID                    341
#define IDD_PAD_FLAGS                   342
#define IDD_GLUE_SPOT                   343
#define IDD_HOLE                        344
#define IDD_SLOT                        345
#define IDD_FP_TEXT                     346
#define IDD_VALUE_TEXT                  347
#define IDD_NET_COMBINE                 348
#define IDD_CHOOSE_NET                  349
#define IDD_SAVE_LIB                    350
#define IDD_ADD_MERGE                   351
#define IDD_STR                         353
#define ID_ADD_POLYLINE                 354
#define IDD_VIAS_GRID                   354
#define IDD_ADD_MERGE1                  355
#define IDD_DUPLICATE_CHANNEL           355
#define IDD_PDF_LAYERS                  356
#define IDD_PROTECT                     357
#define IDD_OPENSCAD                    358
#define IDD_ADD_CODE                    359
#define IDD_ADD_CODE2                   361
#define IDD_ADD_CODE3                   362
#define ID_FILE_GENERATEHPGLFILE1       364
#define ID_FILE_GENERATEHPGLFILE2       365
#define ID_FILE_GENERATEHPGLFILE3       366
#define ID_FILE_GENERATEHPGLFILE4       367
#define ID_FILE_GENERATEHPGLFILE5       368
#define ID_FILE_GENERATEHPGLFILE6       369
#define ID_FILE_GENERATEHPGLFILE7       370
#define ID_FILE_GENERATEHPGLFILE8       371
#define ID_FILE_GENERATEHPGLFILE9       372
#define ID_FILE_GENERATEHPGLFILE10      373
#define ID_FILE_GENERATEHPGLFILE11      374
#define ID_FILE_GENERATEHPGLFILE12      375
#define ID_FILE_GENERATEHPGLFILE13      376
#define ID_FILE_GENERATEHPGLFILE14      377
#define ID_FILE_GENERATEHPGLFILE15      378
#define ID_FILE_OPEN_FROM_START         400
#define ID_FILE_OPEN_FROM_END           1000
#define IDC_EDIT1                       1002
#define IDC_PART_REF                    1002
#define IDC_EDIT_VIA_PAD                1002
#define IDC_EDIT_TEXT                   1002
#define IDC_EDIT_NAME                   1002
#define IDC_EDIT_X                      1002
#define IDC_EDIT_LAYER_1                1002
#define IDC_EDIT_CHAR_HEIGHT            1002
#define IDC_EDIT_FILL                   1002
#define IDC_EDIT_LOG                    1002
#define IDC_EDIT_WIZ_NAME               1002
#define IDC_EDIT_SAVE_NAME              1002
#define IDC_EDIT_PIN_NUM                1002
#define IDC_EDIT_LIB_FOLDER             1002
#define IDC_EDIT_MGR_FOLDER             1002
#define IDC_EDIT_DUP_MESSAGE            1002
#define IDC_EDIT2                       1003
#define IDC_EDIT_VIA_HOLE               1003
#define IDC_FOOTPRINT                   1003
#define IDC_EDIT_HEIGHT                 1003
#define IDC_EDIT_VIA_W                  1003
#define IDC_EDIT_Y                      1003
#define IDC_EDIT_FOLDER                 1003
#define IDC_EDIT_LAYER_2                1003
#define IDC_EDIT_MESSAGE                1003
#define IDC_EDIT_WIZ_NPINS              1003
#define IDC_EDIT_NUM_PINS               1003
#define IDC_EDIT_AUTHOR                 1003
#define IDC_EDIT_IMPORT_AUTHOR          1003
#define IDC_EDIT_NEW_FP_NAME            1003
#define IDC_NET_NAME                    1004
#define IDC_MERGE_NAME                  1004
#define IDC_EDIT_VIA_PAD_W              1004
#define IDC_EDIT_HOLE_W                 1004
#define IDC_EDIT_LIBRARY_FOLDER         1004
#define IDC_EDIT_LAYER_3                1004
#define IDC_EDIT_REF_ID                 1004
#define IDC_PART_PACKAGE                1004
#define IDC_EDIT_SOURCE                 1004
#define IDC_EDIT_IMPORT_SOURCE          1004
#define IDC_EDIT4                       1004
#define IDC_EDIT_INCREMENT              1004
#define IDC_EDIT_FIELD1                 1004
#define IDC_EDIT_VIA_HOLE_W             1005
#define IDC_EDIT_LAYER_4                1005
#define IDC_EDIT_FOOTPRINT              1005
#define IDC_EDIT_DESC                   1005
#define IDC_EDIT_IMPORT_DESC            1005
#define IDC_EDIT5                       1005
#define IDC_MERGE_AREA_CLEARANCE        1005
#define IDC_EDIT_FIELD2                 1005
#define IDC_EDIT_3D_LIB_FOLDER          1005
#define IDC_COMBO_NET                   1006
#define IDC_EDIT_LAYER_5                1006
#define IDC_EDIT6                       1006
#define IDC_FOOTPRINT2                  1006
#define IDC_FOOT_SEARCH                 1006
#define IDC_EDIT_PANEL_HOLE_DIAM        1006
#define IDC_COMBO_WIDTH                 1007
#define IDC_EDIT_LAYER_6                1007
#define IDC_EDIT7                       1007
#define IDC_PANEL_TEXT1                 1007
#define IDC_DEF_NET                     1008
#define IDC_EDIT_LAYER_7                1008
#define IDC_EDIT8                       1008
#define IDC_PANEL_TEXT2                 1008
#define IDC_DEF_CON                     1009
#define IDC_EDIT_LAYER_8                1009
#define IDC_EDIT9                       1009
#define IDC_PANEL_TEXT3                 1009
#define IDC_APPLY_NET                   1010
#define IDC_EDIT_LAYER_9                1010
#define IDC_EDIT10                      1010
#define IDC_PANEL_TEXT4                 1010
#define IDC_APPLY_CON                   1011
#define IDC_EDIT_LAYER_10               1011
#define IDC_EDIT11                      1011
#define IDC_APPLY_SEG                   1012
#define IDC_EDIT_LAYER_11               1012
#define IDC_RADIO_DEF_VIA               1013
#define IDC_RADIO_SET_VIA               1014
#define IDC_EDIT_LAYER_12               1014
#define IDC_EDIT_LAYER_13               1015
#define IDC_EDIT_LAYER_14               1016
#define IDC_PART_LIB_TREE               1017
#define IDC_EDIT_LAYER_15               1017
#define IDC_DEF_WIDTH                   1018
#define IDC_EDIT_LAYER_16               1018
#define IDC_SET_WIDTH                   1019
#define IDC_EDIT_WIDTH                  1020
#define IDC_EDIT_WIDTH2                 1021
#define IDC_EDIT_DEF_WIDTH              1021
#define IDC_LIST_LAYER                  1023
#define IDC_CHECK_MIRROR                1025
#define IDC_RADIO1                      1027
#define IDC_EDIT14                      1027
#define IDC_RADIO2                      1028
#define IDC_X                           1029
#define IDC_RADIO_Z1                    1029
#define IDC_RADIO7                      1029
#define IDC_RADIO_2_1                   1029
#define IDC_REF3                        1029
#define IDC_Y                           1030
#define IDC_RADIO_C2                    1030
#define IDC_RADIO8                      1030
#define IDC_RADIO_2_2                   1030
#define IDC_REF4                        1030
#define IDC_RADIO_G2                    1031
#define IDC_RADIO9                      1031
#define IDC_RADIO_1_1                   1031
#define IDC_RADIO_Z2                    1032
#define IDC_RADIO10                     1032
#define IDC_RADIO_1_2                   1032
#define IDC_LIST_ANGLE                  1033
#define IDC_LIST_NET                    1034
#define IDC_LIST_SIDE                   1036
#define IDC_CHECK_VISIBLE               1038
#define IDC_LIST_PIN                    1039
#define IDC_CHECK_VISIBLE2              1039
#define IDC_CHECK_DEF_POS               1039
#define IDC_CHECK_ADD_THRML             1039
#define IDC_BUTTON_DELETE               1040
#define IDC_CHECK_DEF_POS2              1040
#define IDC_CHECK_REF_NOT_USE           1040
#define IDC_CHECK_NO_THRML              1040
#define IDC_BUTTON_ADD                  1041
#define IDC_CHECK_OCTAGON               1041
#define IDC_RADIO_DEF_WIDTH             1042
#define IDC_BUTTON_DELETE_NOPINS        1042
#define IDC_BUTTON_VAL_VIS              1042
#define IDC_CHECK_WID                   1042
#define IDC_BUTTON_NL_WIDTH             1043
#define IDC_BUTTON_VAL_INVIS            1043
#define IDC_CHECK_PADS                  1043
#define IDC_RADIO_SET_WIDTH             1044
#define IDC_BUTTON_DELETE_1PINS         1044
#define IDC_BUTTON_DELETE_1PIN          1044
#define IDC_CHECK_SEGS                  1044
#define IDC_BUTTON_DELETE2              1045
#define IDC_CHECK_AREAS                 1045
#define IDC_CHECK_HOLES                 1046
#define IDC_CHECK_TEXTS                 1047
#define IDC_CHECK_BOARD                 1048
#define IDC_RADIO_DEF                   1049
#define IDC_CHECK_POLYLINES             1049
#define IDC_RADIO_SET                   1050
#define IDC_CHECK_ANY_LAYER             1050
#define IDC_BUTTON_VISIBLE              1051
#define IDC_CHECK_DEL_ISLAND            1051
#define IDC_BUTTON_EDIT                 1052
#define IDC_CHECK_ADD_THRML2            1052
#define IDC_CHECK_ADD_NEW               1052
#define IDC_BUTTON_SET_W                1053
#define IDC_BUTTON_CANCEL_W             1054
#define IDC_BUTTON_SELECT_ALL           1055
#define IDC_EDIT_NUM_LAYERS             1061
#define IDC_EDIT_DEF_TRACE_W            1062
#define IDC_EDIT_DEF_VIA_W              1063
#define IDC_EDIT_DEF_VIA_HOLE           1064
#define IDC_LIST_WIDTH_MENU             1065
#define IDC_CHECK_OVERIDE               1069
#define IDC_EDIT_OVERIDE                1070
#define IDC_EDIT_MASK                   1071
#define IDC_EDIT_CLEARANCE              1072
#define IDC_EDIT_ADD_PIN                1073
#define IDC_COMBO_PLACEMENT_GRID        1074
#define IDC_COMBO_ROUTING_GRID          1075
#define IDC_STATIC1                     1075
#define IDC_STATIC_VISIBLE_GRID         1076
#define IDC_STATIC2                     1076
#define IDC_STATIC_PLACEMENT_GRID       1077
#define IDC_STATIC3                     1077
#define IDC_STATIC_ROUTING_GRID         1078
#define IDC_COMBO_VISIBLE_GRID          1079
#define IDC_RADIO_DRAG                  1140
#define IDC_LIST1                       1141
#define IDC_BUTTON1                     1142
#define IDC_BUTTON_SAVE                 1142
#define IDC_BUTTON_BROWSE_LIB_FOLDER    1142
#define IDC_WIZ_BUTTON_SAVE             1142
#define IDC_BUTTON_MGR_BROWSE           1142
#define IDC_BUTTON_ADD_PART_BROWSE      1142
#define IDC_BUTTON_SAVE_FP_BROWSE       1142
#define IDC_BUTTON2                     1143
#define IDC_BUTTON_DELETE_SETTING       1143
#define IDC_BUTTON3                     1144
#define IDC_RADIO_PART                  1145
#define IDC_BUTTON4                     1145
#define IDC_RADIO_FOOTPRINT             1146
#define IDC_BUTTON5                     1146
#define IDC_BUTTON6                     1147
#define IDC_BUTTON7                     1148
#define IDC_RADIO_PARTS                 1149
#define IDC_BUTTON8                     1149
#define IDC_RADIO_PARTSANDNETS          1150
#define IDC_RADIO_FREEPCB               1151
#define IDC_BUTTON9                     1151
#define IDC_RADIO_PADSPCB               1152
#define IDC_BUTTON10                    1152
#define IDC_RADIO_NETS                  1153
#define IDD_MYFILEDLG                   1154
#define ID_VIEW_FOOTPRINT               1155
#define IDC_STATIC_SNAP_ANGLE           1156
#define IDC_COMBO_SNAP_ANGLE            1157
#define IDC_CHECK_TOP_SILK              1159
#define IDC_CHECKBOTTOM_SOLDER_MASK     1160
#define IDC_CHECK_DRILL                 1161
#define IDC_CHECK_BOTTOM_SILK           1162
#define IDC_CHECK_TOP_SOLDER            1163
#define IDC_CHECK_TOP_COPPER            1164
#define IDC_CHECK_INNER1                1165
#define IDC_CHECK_INNER4                1166
#define IDC_CHECK_BOTTOM_COPPER         1167
#define IDC_CHECK_INNER2                1168
#define IDC_CHECK_INNER3                1169
#define IDC_CHECK_INNER5                1170
#define IDC_BOARD_OUTLINE               1171
#define IDC_MOIRES                      1172
#define IDC_CHECK_INNER_6               1173
#define IDC_CHECK_INNER6                1173
#define IDC_LAYER_DESC                  1174
#define IDC_PREVIEW                     1175
#define IDC_V_CUTOUT_X                  1175
#define IDC_V_CUTOUT_Y                  1176
#define IDC_CHECK_PREVIEW               1177
#define IDC_V_CUTOUT_X2                 1177
#define IDC_V_CUTOUT_Y2                 1178
#define IDC_BMP_QUAD                    1179
#define IDC_180_DEG_1                   1179
#define IDC_EDIT_WIZ_HPINS              1180
#define IDC_180_DEG_2                   1180
#define IDC_EDIT_WIZ_VPINS              1181
#define IDC_EDIT_WIZ_HD                 1182
#define IDC_COMBO_WIZ_SHAPE             1183
#define IDC_CHECK_INNER7                1183
#define IDC_EDIT_WIZ_Y                  1184
#define IDC_CHECK_INNER9                1184
#define IDC_EDIT_WIZ_X                  1185
#define IDC_CHECK_INNER12               1185
#define IDC_EDIT_E                      1186
#define IDC_CHECK_INNER8                1186
#define IDC_EDIT_C1                     1187
#define IDC_CHECK_INNER10               1187
#define IDC_EDIT_G1                     1188
#define IDC_CHECK_INNER11               1188
#define IDC_EDIT_Z1                     1189
#define IDC_CHECK_INNER13               1189
#define IDC_EDIT_C2                     1190
#define IDC_CHECK_INNER14               1190
#define IDC_EDIT_G2                     1191
#define IDC_EDIT_Z2                     1192
#define IDC_COMBO_WIZ_UNITS             1193
#define IDC_RADIO_C1                    1194
#define IDC_CHECK_SCRIBING              1194
#define IDC_RADIO_G1                    1195
#define IDC_CHECK_REFINETOP             1195
#define IDC_COMBO_PIN1                  1196
#define IDC_CHECK_REFINEBOT             1196
#define IDC_EDIT_RAD                    1197
#define IDC_CHECK_HILITE                1197
#define IDC_COMBO_WIZ_TYPE              1198
#define IDC_PREVIEW2                    1199
#define IDC_COMBO_LIBS                  1203
#define IDC_COMBO_SAVE_HEADING          1204
#define IDC_RADIO_ADD_PIN               1205
#define IDC_RADIO_ADD_ROW               1206
#define IDC_RADIO_SMT                   1207
#define IDC_RADIO_TH                    1208
#define IDC_EDIT_HOLE_DIAM              1209
#define IDC_RADIO_SMT2                  1211
#define IDC_RADIO_SAME_AS               1211
#define IDC_COMBO_PIN_UNITS             1214
#define IDC_EDIT_TOP_PAD_L              1215
#define IDC_COMBO_INNER_PAD_SHAPE       1216
#define IDC_EDIT_INNER_PAD_W            1217
#define IDC_EDIT_INNER_PAD_L            1218
#define IDC_EDIT_TOP_PAD_L2             1219
#define IDC_EDIT_TOP_PAD_RAD            1220
#define IDC_EDIT_INNER_PAD_RAD          1221
#define IDC_EDIT_BOTTOM_PAD_RAD         1222
#define IDC_EDIT_BOTTOM_PAD_RAD2        1223
#define IDC_RADIO_DRAG_PIN              1224
#define IDC_RADIO_SET_PIN_POS           1225
#define IDC_EDIT_PIN_X                  1226
#define IDC_EDIT_PIN_Y                  1227
#define IDC_EDIT_BOTTOM_PAD_RAD3        1228
#define IDC_COMBO_SAME_AS_PIN           1229
#define IDC_EDIT_TOP_PAD_L3             1230
#define IDC_EDIT_ROW_SPACING            1231
#define IDC_EDIT_TOP_PAD_RAD2           1232
#define IDC_COMBO_ROW_ORIENT            1233
#define IDC_EDIT_TOP_PAD_RAD3           1234
#define IDC_COMBO_PAD_ORIENT            1236
#define IDC_EDIT_TOP_PAD_W              1237
#define IDC_COMBO_TOP_PAD_SHAPE         1238
#define IDC_COMBO_TOP_PAD_SHAPE2        1239
#define IDC_COMBO_TOP_PAD_SHAPE3        1240
#define IDC_CHECK_INNER_SAME_AS         1241
#define IDC_EDIT_BOTTOM_PAD_L           1242
#define IDC_COMBO_BOTTOM_PAD_SHAPE      1243
#define IDC_EDIT1_BOTTOM_PAD_W          1244
#define IDC_EDIT_BOTTOM_PAD_W           1244
#define IDC_CHECK_BOTTOM_SAME_AS        1245
#define IDC_RADIO_OPEN                  1246
#define IDC_COMBO_BOTTOM_PAD_SHAPE2     1246
#define IDC_RADIO_CLOSED                1247
#define IDC_COMBO_BOTTOM_PAD_SHAPE3     1247
#define IDC_STATIC_UNITS                1248
#define IDC_EDIT_BOTTOM_PAD_W2          1248
#define IDC_COMBO_UNITS                 1249
#define IDC_EDIT_BOTTOM_PAD_W3          1249
#define IDC_RADIO_FULL                  1250
#define IDC_EDIT_BOTTOM_PAD_L2          1250
#define IDC_COMBO_UNITS2                1250
#define IDC_COMBO_CLR                   1250
#define IDC_RADIO_EDGE                  1251
#define IDC_EDIT_BOTTOM_PAD_L3          1251
#define IDC_COMBO_UNITS3                1251
#define IDC_COMBO_RESOLUTION            1251
#define IDC_RADIO_NONE                  1252
#define IDC_EDIT_TOP_PAD_W2             1252
#define IDC_EDIT_TOP_PAD_W3             1253
#define IDC_RADIO_HATCH_NONE            1254
#define IDC_CHECK_BOTTOM_SAME_AS2       1254
#define IDC_RADIO_HATCH_FULL            1255
#define IDC_RADIO_HATCH_EDGE            1256
#define IDC_COMBO_CORNER_UNITS          1258
#define IDC_COMBO_ADD_PART_UNITS        1259
#define IDC_COMBO_ADD_POLY_UNITS        1260
#define IDC_COMBO_ADD_TEXT_UNITS        1261
#define IDC_COMBO_EDIT_NET_UNITS        1262
#define IDC_COMBO_REF_TEXT_UNITS        1263
#define IDC_COMBO_CAD_UNITS             1264
#define IDC_EDIT_FP_REF_CHAR_HEIGHT     1265
#define IDC_PANEL_HOLE_CNT              1265
#define IDC_COMBO_FP_REF_TEXT_UNITS     1266
#define IDC_PANEL_HOLE_CNT2             1266
#define IDC_SELECT_REF                  1266
#define IDC_EDIT_FP_REF_WIDTH           1267
#define IDC_EDIT_FP_REF_DEF_WIDTH       1268
#define IDC_RADIO_FP_REF_SET            1269
#define IDC_RADIO_FP_REF_DEF            1270
#define ID_WIZ_BUTTON_EXIT              1271
#define IDC_STATIC_WIZ_PREVIEW          1272
#define IDC_CHECK_CAD_PILOT             1273
#define IDC_EDIT_CAD_PILOT_DIAM         1274
#define IDC_COMBO_MGR_FILE              1275
#define IDC_BUTTON_MAKE_PDF             1276
#define IDC_EDIT_ADD_AUTHOR             1277
#define IDC_EDIT_ADD_SOURCE             1278
#define IDC_EDIT_ADD_DESC               1279
#define IDC_COMBO_PAGE_SIZE             1280
#define IDC_RADIO_REPLACE_ALL           1282
#define IDC_RADIO_REPLACE_THIS          1283
#define IDC_EDIT_CAD_MIN_SSW            1284
#define IDC_EDIT_ADD_PART_LIB           1285
#define IDC_EDIT_CAD_MIN_SSW2           1285
#define IDC_EDIT_CAD_HIGH_W             1285
#define IDC_EDIT_FP_SAVE_FOLDER         1286
#define IDC_CHECK_AUTOSAVE              1287
#define IDC_EDIT_AUTO_INTERVAL          1288
#define IDC_EDIT_CAD_THERMALWID         1289
#define IDC_RADIO_OFFBOARD              1290
#define IDC_EDIT_CAD_HOLE_CLEARANCE     1290
#define IDC_EDIT_CAD_THERMALWID2        1291
#define IDC_EDIT_CAD_OUTLINE_WID        1291
#define IDC_EDIT3                       1291
#define IDC_EDIT_PIN_NAME               1291
#define IDC_EDIT_OUTPUT                 1291
#define IDC_EDIT_GLUE_W                 1291
#define IDC_EDIT_CAD_ANN_PINS           1292
#define IDC_EDIT_PIN_NAME2              1292
#define IDC_EDIT_PIN_DESCRIPTION        1292
#define IDC_EDIT_CAD_ANN_VIAS           1293
#define IDC_COMBO1                      1294
#define IDC_EDIT_CAD_SHRINK_PASTE       1294
#define IDC_RADIO3                      1295
#define IDC_COMBO2                      1295
#define IDC_EDIT_N_X                    1295
#define IDC_RADIO4                      1296
#define IDC_COMBO3                      1296
#define IDC_EDIT_CAD_THERMALWID3        1296
#define IDC_EDIT_CAD_THERMALCL          1296
#define IDC_RADIO5                      1297
#define IDC_COMBO4                      1297
#define IDC_EDIT_N_Y                    1297
#define IDC_RADIO6                      1298
#define IDC_COMBO5                      1298
#define IDC_EDIT_SP_X                   1298
#define IDC_RADIO_KEEP_PARTS_AND_CONNECTIONS 1299
#define IDC_COMBO6                      1299
#define IDC_EDIT_SP_Y                   1299
#define IDC_RADIO11                     1299
#define IDC_RADIO_1_3                   1299
#define IDC_RADIO_KEEP_PARTS_NO_CONNECTIONS 1300
#define IDC_COMBO7                      1300
#define IDC_RADIO12                     1300
#define IDC_RADIO_1_4                   1300
#define IDC_EDIT_DPI                    1300
#define IDC_RADIO_REMOVE_PARTS          1301
#define IDC_COMBO8                      1301
#define IDC_EDIT_PNG_AA                 1301
#define IDC_CHECK_SHOW_UNROUTED         1302
#define IDC_COMBO9                      1302
#define IDC_RADIO_SEGMENT               1303
#define IDC_COMBO10                     1303
#define IDC_CHECK_AS_PART               1303
#define IDC_RADIO_TRACE                 1304
#define IDC_COMBO11                     1304
#define IDC_CHECK_SHOW_UNROUTED3        1304
#define IDC_CHECK_CHESS                 1304
#define IDC_RADIO_NET                   1305
#define IDC_COMBO12                     1305
#define IDC_CHECK1                      1306
#define IDC_COMBO13                     1306
#define IDC_CHECK2                      1307
#define IDC_COMBO14                     1307
#define IDC_CHECK3                      1308
#define IDC_COMBO15                     1308
#define IDC_LIST_PINS                   1309
#define IDC_COMBO16                     1309
#define IDC_STATIC_MYMESSAGE            1310
#define IDC_VIA_WIDTH                   1311
#define IDC_VIA_HOLE_WIDTH              1312
#define IDC_RADIO_MOD_TV                1313
#define IDC_RADIO_MOD_T                 1314
#define IDC_RADIO_MOD_V                 1315
#define IDC_RADIO_REVERT_VIAS           1316
#define IDC_RADIO_REVERT_TRACES         1317
#define IDC_RADIO_SET_TRACE_WIDTH       1318
#define IDC_CHECK_NL_COMP               1319
#define IDC_STATIC_MYMESSAGE_2          1321
#define IDC_RADIO_DEL_GROUP_NETS        1322
#define IDC_RADIO_USE_GROUP_NETS        1323
#define IDC_RADIO_USE_SELECTED_NETS     1324
#define IDC_RADIO_USE_GROUP_REF         1325
#define IDC_RADIO_USE_NEXT_REF          1326
#define IDC_RADIO_ADD_REF_OFFSET        1327
#define IDC_EDIT_REF_OFFSET             1328
#define IDC_LIST_SELECT_GROUP_NETS      1330
#define IDC_RADIO_USE_SUFFIX            1331
#define IDC_RADIO_MAKE_NEW_NAMES        1332
#define IDC_RADIO_USE_GROUP_REF2        1333
#define IDC_RADIO_OFFSET                1334
#define IDC_COMBO_GROUP_UNITS           1335
#define IDC_EDIT_GROUP_X                1336
#define IDC_EDIT_GROUP_Y                1337
#define IDC_RADIO_RETAIN_ALL            1338
#define IDC_RADIO_RETAIN_TRACES         1339
#define IDC_CHECK_KEEP_TRACES           1340
#define IDC_CHECK_KEEP_STUBS            1341
#define IDC_CHECK_KEEP_AREAS            1342
#define IDC_STATIC_1                    1343
#define IDC_REMOVE_NOT_NL               1343
#define IDC_STATIC_2                    1344
#define IDC_REMOVE_OLD_NET              1344
#define IDC_STATIC_3                    1345
#define IDC_RENAME_SAME                 1345
#define IDC_STATIC_4                    1346
#define IDC_CHECK_KEEP_AREAS2           1346
#define IDC_RELOAD_LIB                  1346
#define IDC_STATIC_5                    1347
#define IDC_STATIC_6                    1348
#define IDC_STATIC_7                    1349
#define IDC_STATIC_8                    1350
#define IDC_BUTTON_LIB                  1351
#define IDC_STATIC_9                    1351
#define IDC_BUTTON_FOLDER               1352
#define IDC_STATIC_10                   1352
#define IDC_BUTTON_LIB2                 1352
#define IDC_BUTTON_PRF                  1352
#define IDC_BUTTON_DEF                  1353
#define IDC_STATIC_11                   1353
#define IDC_BUTTON_LIB3                 1353
#define IDC_BUTTON_3D_LIB               1353
#define IDC_STATIC_12                   1354
#define IDC_BUTTON_FOLDER2              1354
#define IDC_CHECK_VERBOSE               1355
#define IDC_STATIC_13                   1355
#define IDC_CHECK_INFO                  1356
#define IDC_STATIC_14                   1356
#define IDC_COMBO_BOUNDS                1357
#define IDC_STATIC_15                   1357
#define IDC_COMBO_SIGNALS               1358
#define IDC_STATIC_16                   1358
#define IDC_EDIT_SES                    1361
#define IDC_BUTTON_BROWSE               1363
#define IDC_CHECK_LOAD                  1364
#define IDC_EDIT_FILE                   1365
#define IDC_CHECK_BD                    1366
#define IDC_CHECK_TOP_PASTE             1367
#define IDC_CHECK_BOTTOM_PASTE          1368
#define IDC_BUTTON_NEW_NET              1369
#define ID_MY_OK                        1370
#define IDC_CHECK_90                    1371
#define ID_HIDE_ME                      1372
#define IDC_CHECK_ALL_GERBERS           1374
#define IDC_CHECK_NEGATIVE              1376
#define IDC_CHECK_MIRROR_BOTTOM         1377
#define IDC_RADIO_STRAIGHT              1379
#define IDC_RADIO_ARC_CW                1380
#define IDC_RADIO_ARC_CCW               1381
#define IDC_CHECK_SMT_THERMALS          1382
#define IDC_CHECK_CAM                   1385
#define IDC_CHECK_STATS                 1387
#define IDC_CHECK_PARTS                 1388
#define IDC_CHECK_DRC                   1389
#define IDC_RADIO_INCH                  1390
#define IDC_RADIO_MM                    1391
#define IDC_CHECK_CONNECTIVITY          1392
#define IDC_CHECK_DRC_PARAMS            1393
#define IDC_CHECK_AREA                  1396
#define IDC_CHECK_NO_MASK               1397
#define IDC_CHECK_NO_AREA               1398
#define IDC_CHECK_AREA_THERMAL          1399
#define IDC_CHECK_FROM_TO               1400
#define IDC_RADIO_ALL                   1402
#define IDC_RADIO_LOCKED                1403
#define IDC_RADIO_NET_LOCKED            1404
#define IDC_EDIT_DIAMETER               1405
#define IDC_RADIO_SET_SIZE              1406
#define IDC_EDIT_TRAVEL                 1407
#define IDC_COMBO_DIRECTION             1408
#define IDC_EDIT_VALUE                  1409
#define IDC_CHECK_LAYER_3               1410
#define IDC_CHECK_LAYER_4               1411
#define IDC_CHECK_LAYER_5               1412
#define IDC_CHECK_LAYER_6               1413
#define IDC_CHECK_LAYER_7               1414
#define IDC_CHECK_LAYER_8               1415
#define IDC_CHECK_LAYER_9               1416
#define IDC_CHECK_LAYER_10              1417
#define IDC_CHECK_LAYER_11              1418
#define IDC_CHECK_LAYER_12              1419
#define IDC_CHECK_LAYER_13              1420
#define IDC_CHECK_LAYER_14              1421
#define IDC_CHECK_LAYER_15              1422
#define IDC_CHECK_LAYER_16              1423
#define IDC_CHECK_LAYER_17              1424
#define IDC_CHECK_LAYER_18              1425
#define IDC_CHECK_LAYER_19              1426
#define IDC_CHECK_LAYER_20              1427
#define IDC_CHECK_LAYER_21              1428
#define IDC_CHECK_LAYER_22              1429
#define IDC_CHECK_LAYER_23              1430
#define IDC_CHECK_LAYER_24              1431
#define IDC_CHECK_LAYER_25              1432
#define IDC_CHECK_LAYER_26              1433
#define IDC_CHECK_LAYER_27              1434
#define IDC_CHECK_LAYER_28              1435
#define IDC_CHECK_LAYER_29              1436
#define IDC_CHECK_LAYER_30              1437
#define IDC_CHECK_LAYER_31              1438
#define IDC_DLG_MERGE_UNITS             1438
#define IDC_COMBO_ANGLE                 1439
#define IDC_CHECK_LAYER_32              1439
#define IDC_CHECK_LAYER_SYS_CLRS        1439
#define IDC_CHECK_AT                    1440
#define IDC_EDIT_W                      1440
#define IDC_CHECK_LAYER_SYS_CLRS2       1440
#define IDC_CHECK_REF_VALUE             1440
#define IDC_CHECK_REF                   1440
#define IDC_CHECK4                      1441
#define IDC_CLR_PADS                    1441
#define IDC_CHECK_LAYER_SYS_CLRS3       1441
#define IDC_CHECK_VALUE                 1441
#define IDC_RADIO_CCW                   1442
#define IDC_CHECK_NET_SEL               1442
#define IDC_CHECK_PACKAGE               1442
#define IDC_CHECK_VALUE2                1442
#define IDC_RADIO_CW                    1443
#define IDC_CLR_SEGS                    1443
#define IDC_RADIO_3_1                   1444
#define IDC_CLR_AREAS                   1444
#define IDC_RADIO_3_2                   1445
#define IDC_CLR_HOLES                   1445
#define IDC_RADIO_2_3                   1446
#define IDC_CLR_TEXTS                   1446
#define IDC_RADIO_2_4                   1447
#define IDC_CLR_BOARD                   1447
#define IDC_RADIO_3_3                   1448
#define IDC_CLR_POLYLINES               1448
#define IDC_RADIO_3_4                   1449
#define IDC_COMBO_NET_SEL               1449
#define IDC_RADIO_TOP                   1450
#define IDC_CLR_THERMAL                 1450
#define IDC_RADIO_BOTTOM                1451
#define IDC_COMBO_SETTING               1451
#define IDC_COMBO_SETTINGS              1451
#define IDC_BUTTON_DONE                 1452
#define IDC_EDIT_NEW_NAME               1452
#define IDC_COMBO_X_EDGE                1453
#define IDC_EDIT_STR                    1453
#define IDC_COMBO_Y_EDGE                1454
#define IDC_UNITS                       1454
#define IDC_LIST_FP2                    1455
#define IDC_EDIT_SPACE_X                1455
#define IDC_CHECK_AUTORAT_DISABLE       1456
#define IDC_EDIT_SPACE_Y                1456
#define IDC_EDIT_MIN_PINS               1457
#define IDC_EDIT_VIA_SIZE               1457
#define IDC_AREA_WIDTH                  1458
#define IDC_EDIT_HOLE_SIZE              1458
#define IDC_BUTTON_LAYER_1              1459
#define IDC_SUFF                        1459
#define IDC_BUTTON_LAYER_2              1460
#define IDC_BUTTON_LAYER_3              1461
#define IDC_BUTTON_LAYER_4              1462
#define IDC_BUTTON_LAYER_5              1463
#define IDC_BUTTON_LAYER_6              1464
#define IDC_BUTTON_LAYER_7              1465
#define IDC_BUTTON_LAYER_8              1466
#define IDC_BUTTON_LAYER_9              1467
#define IDC_BUTTON_LAYER_10             1468
#define IDC_BUTTON_LAYER_11             1469
#define IDC_BUTTON_LAYER_12             1470
#define IDC_BUTTON_LAYER_13             1471
#define IDC_BUTTON_LAYER_14             1472
#define IDC_BUTTON_LAYER_15             1473
#define IDC_BUTTON_LAYER_16             1474
#define IDC_BUTTON_LAYER_17             1475
#define IDC_BUTTON_LAYER_18             1476
#define IDC_BUTTON_LAYER_19             1477
#define IDC_BUTTON_LAYER_20             1478
#define IDC_BUTTON_LAYER_21             1479
#define IDC_BUTTON_LAYER_22             1480
#define IDC_BUTTON_LAYER_23             1481
#define IDC_BUTTON_LAYER_24             1482
#define IDC_BUTTON_LAYER_25             1483
#define IDC_BUTTON_LAYER_26             1484
#define IDC_BUTTON_LAYER_27             1485
#define IDC_BUTTON_LAYER_28             1486
#define IDC_BUTTON_LAYER_29             1487
#define IDC_BUTTON_LAYER_30             1488
#define IDC_BUTTON_LAYER_31             1489
#define IDC_STATIC_LAYER_1              1490
#define IDC_STATIC_LAYER_2              1491
#define IDC_STATIC_LAYER_3              1492
#define IDC_STATIC_LAYER_4              1493
#define IDC_STATIC_LAYER_5              1494
#define IDC_STATIC_LAYER_6              1495
#define IDC_STATIC_LAYER_7              1496
#define IDC_STATIC_LAYER_8              1497
#define IDC_STATIC_LAYER_9              1498
#define IDC_STATIC_LAYER_10             1499
#define IDC_STATIC_LAYER_11             1500
#define IDC_STATIC_LAYER_12             1501
#define IDC_STATIC_LAYER_13             1502
#define IDC_STATIC_LAYER_14             1503
#define IDC_STATIC_LAYER_15             1504
#define IDC_STATIC_LAYER_16             1505
#define IDC_STATIC_LAYER_17             1506
#define IDC_STATIC_LAYER_18             1507
#define IDC_STATIC_LAYER_19             1508
#define IDC_STATIC_LAYER_20             1509
#define IDC_STATIC_LAYER_21             1510
#define IDC_STATIC_LAYER_22             1511
#define IDC_STATIC_LAYER_23             1512
#define IDC_STATIC_LAYER_24             1513
#define IDC_STATIC_LAYER_25             1514
#define IDC_STATIC_LAYER_26             1515
#define IDC_STATIC_LAYER_27             1516
#define IDC_STATIC_LAYER_28             1517
#define IDC_STATIC_LAYER_29             1518
#define IDC_STATIC_LAYER_30             1519
#define IDC_STATIC_LAYER_31             1520
#define ID_HELP_FPCROUTE                1521
#define IDC_EDIT_MARGIN                 1521
#define IDC_STATIC_LAYER_6A             1522
#define IDC_RADIO_EE                    1522
#define IDC_STATIC_LAYER_6B             1523
#define IDC_RADIO_DE                    1523
#define IDC_STATIC_LAYER_6C             1524
#define IDC_PROTECT_AFTER_GERBER        1524
#define IDC_CHECK_MARGIN                1525
#define IDC_PROTECT_ARCH_PRESENT        1525
#define IDC_CHECK_USE_FONT              1526
#define IDC_PROTECT_AFTER_IMPORT        1526
#define IDC_EXTRUSION_VALUE             1526
#define IDC_TEXT_FONTS                  1527
#define IDC_TEXT_FONT                   1527
#define IDC_RADIO_EE2                   1527
#define IDC_EXTRUSION_ROT               1527
#define IDC_RADIO_DE2                   1528
#define IDC_ROT_X                       1528
#define IDC_ROT_Y                       1529
#define IDC_ROT_Z                       1530
#define IDC_MOV_X                       1531
#define IDC_MOV_Y                       1532
#define IDC_MOV_Z                       1533
#define IDC_CORNER_ROUNDING             1534
#define IDC_ROT_VTX1                    1535
#define IDC_RADIO_BODY                  1536
#define IDC_RADIO_HOLE                  1537
#define IDC_MATRIX_X                    1538
#define IDC_MATRIX_Y                    1539
#define IDC_MATRIX_DX                   1540
#define IDC_MATRIX_DY                   1541
#define IDC_MATRIX_Z                    1542
#define IDC_MATRIX_DZ                   1543
#define IDC_STATIC_DZ                   1544
#define IDC_STATIC_DY                   1545
#define IDC_STATIC_DX                   1546
#define IDC_STATIC_EX                   1547
#define IDC_STATIC_EX_R                 1548
#define IDC_LIFT                        1549
#define IDC_STATIC_EX2                  1550
#define IDC_GLOBAL_ROT                  1551
#define IDC_CODE                        1553
#define IDC_REF2                        1553
#define IDC_STATIC_EX_R2                1554
#define IDC_COMBO_Y                     1554
#define IDC_EXTRUSION_SCALE             1555
#define IDC_COMBO_X                     1555
#define IDC_STATIC_EX3                  1556
#define IDC_RADIO_90DEG                 1556
#define IDC_HULL                        1557
#define IDC_LIKE_CAP                    1558
#define IDC_RADIO1X1                    1558
#define IDC_RADIO2X1                    1559
#define IDC_RADIO1X2                    1560
#define IDC_RADIO2X2                    1561
#define IDC_CHECK_ORIGIN                1562
#define ID_FP_SET_ORIGIN                32757
#define ID_FP_FIRST_VTX                 32758
#define ID_FILE_SEL_FOLDER              32759
#define ID_FILE_RELOAD_MENU             32760
#define ID_ADD_GRAPHICLINE              32761
#define ID_ALIGN_X                      32762
#define ID_ALIGN_Y                      32763
#define ID_ALIGN_XY                     32764
#define ID_ALIGN_MID_X                  32765
#define ID_ALIGN_MID_Y                  32766
#define ID_ALIGN_MID_XY                 32767
#define ID_ALIGN_45_X                   32768
#define ID_ALIGN_45_Y                   32769
#define ID_ALIGN_45_XY                  32770
#define ID_BUTTON32771                  32771
#define ID_FP_MOVE                      32772
#define ID_FP_EDITPROPERTIES            32773
#define ID_FP_DELETE                    32774
#define ID_FP_INSERTCORNER              32775
#define ID_FP_CONVERTTOSTRAIGHT         32776
#define ID_FP_CONVERTTOARC              32777
#define ID_FP_CONVERTTOARC32778         32778
#define ID_FP_DELETEOUTLINE             32779
#define ID_FP_MOVE32780                 32780
#define ID_FP_SETPOSITION               32781
#define ID_FP_DELETECORNER              32782
#define ID_FP_DELETEPOLYLINE            32783
#define ID_ALIGN_MIDPOINT_X             32784
#define ID_ALIGN_MIDPOINT_Y             32785
#define ID_FP_MOVE_REF                  32786
#define ID_FP_CHANGESIZE_REF            32787
#define ID_FP_OPENSCAD                  32788
#define ID_FP_TOOLS_RETURN              32789
#define ID_FP_TOOLS_FOOTPRINTWIZARD     32790
#define ID_TOOLS_FOOTPRINTLIBRARYMANAGER 32791
#define ID_FILE_EXPORTNETLIST           32792
#define ID_HELP_GOTOWEBSITE             32793
#define ID_HELP_USERGUIDE               32794
#define ID_HELP_GOTOFAQ                 32795
#define ID_ALIGN_BETWEEN                32796
#define ID_PART_SET_REF                 32797
#define ID_RATLINE_CHANGEPIN            32798
#define ID_FILE_IMPORTNETLIST           32799
#define ID_TOOLS_DRC                    32800
#define ID_FILE_RELOADNETLIST           32801
#define ID_TOOLS_CLEAR_DRC              32802
#define ID_TOOLS_SHOWDRCERRORLIST       32803
#define ID_VIEW_FINDPART                32804
#define ID_ADD_TEXT32805                32805
#define ID_TOOLS_SETORIGIN              32806
#define ID_FILE_SAVE_VERSION            32807
#define ID_FP_TEXT_DELETE               32809
#define ID_FP_TEXT_MOVE                 32810
#define ID_FP_TEXT_EDIT                 32811
#define ID_FP_ADD_PIN                   32812
#define ID_FP_ADD_POLY                  32813
#define ID_FP_ADD_TEXT                  32814
#define ID_NONE_FOOTPRINTWIZARD         32815
#define ID_NONE_FOOTPRINTEDITOR         32816
#define ID_Menu32817                    32817
#define ID_NONE_CHECKPARTSANDNETS       32818
#define ID_GEN_OPENSCAD                 32819
#define ID_NONE_CLEARDRCERRORS          32820
#define ID_NONE_DRC                     32821
#define ID_NONE_VIEWALL                 32822
#define ID_NONE_ROUTEALL                32823
#define ID_NONE_RETURNTOPCB             32824
#define ID_TOOLS_CHECK_PARTS_NETS       32825
#define ID_TOOLS_CHECK_CONNECTIVITY     32826
#define ID_OP_HATCHSTYLE                32828
#define ID_PART_CHANGESIDE              32838
#define ID_PART_ROTATE                  32839
#define ID_AREAEDGE_ADDCUTOUT           32840
#define ID_AREACORNER_ADDCUTOUT         32841
#define ID_CONNECT_SETWIDTH             32842
#define ID_NET_SETWIDTH                 32843
#define ID_CONNECT_UNROUTETRACE         32844
#define ID_CONNECT_DELETETRACE          32845
#define ID_NET_EDITNET                  32846
#define ID_CONNECT_CHANGELAYER          32847
#define ID_NET_CHANGELAYER              32848
#define ID_SEGMENT_CHANGELAYER          32849
#define ID_TOOLS_MOVEORIGIN             32850
#define ID_GROUP_MOVE                   32851
#define ID_HELP_KEYBOARDSHORTCUTS       32852
#define ID_VIEW_LOG                     32853
#define ID_TOOLS_CHECKCOPPERAREAS       32855
#define ID_AREAEDGE_ADDNEWAREA          32856
#define ID_AREACORNER_ADDNEWAREA        32857
#define ID_AREACORNER_DELETECUTOUT      32858
#define ID_AREAEDGE_DELETECUTOUT        32859
#define ID_ENDVERTEX_SETSIZE            32860
#define ID_VERTEX_SETSIZE               32861
#define ID_SEGMENT_ADDVERTEX            32862
#define ID_AREAEDGE_CHANGELAYER         32863
#define ID_AREACORNER_CHANGELAYER       32864
#define ID_TOOLS_CHECKTRACES            32865
#define ID_AREAEDGE_APPLYCLEARANCES     32866
#define ID_GROUP_SAVETOFILE             32867
#define ID_GROUP_PASTEFROMFILE          32868
#define ID_SELECTALL                    32869
#define ID_GROUP_PASTEFROMFILE32870     32870
#define ID_Menu32871                    32871
#define ID_GROUP_COPY                   32872
#define ID_GROUP_CUT                    32873
#define ID_Menu32874                    32874
#define ID_EDIT_PASTEFROMFILE           32875
#define ID_VERTEX_CONNECTTOPIN          32876
#define ID_GROUP_DELETE                 32877
#define ID_STATIC_HIGHLIGHT             32878
#define ID_CANCEL_HIGHLIGHT             32879
#define ID_Menu32878                    32880
#define ID_Menu32881                    32881
#define ID_FILE_                        32882
#define ID_Menu32883                    32883
#define ID_PRINT_PDF                    32884
#define ID_SES_FILE_IMPORT              32885
#define ID_DSN_FILE_EXPORT              32886
#define ID_TOOLS_OPENONLINEAUTOROUTER   32887
#define ID_HELP_FREEROUTINGWEBSITE      32888
#define ID_EDIT_SAVEGROUPTOFILE         32889
#define ID_PRINT                        32890
#define ID_PRINT_BUTTON                 32890
#define ID_IMAGE1                       32891
#define ID_IMAGE2                       32892
#define ID_HELP_USERGUIDE_PDF           32893
#define ID_TOOLS_MOVEORIGIN_FP          32895
#define ID_NONE_MOVEORIGIN              32896
#define ID_IMAGE1DEL                    32897
#define ID_IMAGE2DEL                    32898
#define ID_INVERTCOLORS                 32899
#define ID_SWAPIMAGES                   32900
#define ID_GROUP_ROTATE                 32901
#define ID_REF_SHOWPART                 32902
#define ID_AREA_SIDESTYLE               32904
#define ID_NONE_REPEATDRC               32905
#define ID_TOOLS_REPEATDRC              32906
#define ID_CHANNEL_DUPLICATION          32907
#define ID_FILE_GENERATEREPORTFILE      32909
#define ID_FILE_GENERATE_3D             32910
#define ID_ADD_CENTOID                  32911
#define ID_ADD_ADHESIVESPOT             32912
#define ID_Menu32913                    32913
#define ID_CENTROID_SETPARAMETERS       32914
#define ID_CENTROID_MOVE                32915
#define ID_ADD_SLOT                     32916
#define ID_ADD_VALUETEXT                32917
#define ID_Menu32918                    32918
#define ID_Menu32919                    32919
#define ID_ADHESIVE                     32921
#define ID_FP_EDIT                      32922
#define ID_FP_MOVE32923                 32923
#define ID_FP_DELETE32924               32924
#define ID_VALUE                        32925
#define ID_VALUE_MOVE                   32926
#define ID_VALUE_CHANGESIZE             32927
#define ID_VALUE_SHOWPART               32928
#define ID_ADHESIVE_EDIT                32929
#define ID_ADHESIVE_MOVE                32930
#define ID_ADHESIVE_DELETE              32931
#define ID_PART_EDITVALUE               32932
#define ID_CENTROID_ROTATEAXIS          32933
#define ID_PART_ROTATECOUNTERCLOCKWISE  32934
#define ID_REF_ROTATECW                 32935
#define ID_REF_ROTATECCW                32936
#define ID_VALUE_ROTATECW               32937
#define ID_VALUE_ROTATECCW              32938
#define ID_PROJECT_COMBINENETS          32939
#define ID_PROJECT_COMBINEBOARD         32940
#define ID_SEGMENT_MOVE                 32941
#define ID_FILE_LOADLIBRARYASPROJECT    32942
#define ID_FILE_SAVEPROJECTASLIBRARY    32943
#define ID_HELP_USERGUIDESUPPLEMENT_PDF 32944
#define ID_TOOLS_REPEAT_GEN_CAM         32945
#define ID_SEL_ARC_EL                   32946
#define ID_SEL_VIA_EL                   32947
#define IDC_REF_TO_TEXT                 32949
#define IDC_VALUE_TO_TEXT               32950
#define ID_SWITCH_TO_ECDS               32951
#define ID_ALIGN_BETWEEN_X              32952
#define ID_MAX_NUM_COMMANDS             32952
#define ID_ALIGN_BETWEEN_Y              32953
#define ID_FILE_GERBER_VIEWER1          32960
#define ID_FILE_GERBER_VIEWER2          32961
#define ID_FILE_GERBER_VIEWER3          32962
#define ID_RUN_INFO_BOX                 32963
#define ID_RUN_LIB_MAN                  32964
#define ID_RUN_INDUCTOR                 32966
#define ID_RUN_RND_CORNERS              32967
#define ID_RUN_REPLACE                  32968
#define ID_RUN_SHOW_NET                 32969
#define ID_RUN_INSERT_NETS              32970
#define ID_RUN_INSERT_REPORT            32971
#define ID_RUN_EXP_TANGO                32972
#define ID_RUN_EXP_DXF                  32973
#define ID_RUN_IMP_TANGO                32974
#define ID_RUN_IMP_DXF                  32975
#define ID_RUN_IMP_BMP                  32976
#define ID_ADD_CODE                     32980
#define ID_ADD_CODE2                    32981
#define ID_ADD_CODE3                    32982
#define ID_FILE_CAM1                    33001
#define ID_FILE_CAM2                    33002
#define ID_FILE_CAM3                    33003
#define ID_FILE_CAM4                    33004
#define ID_FILE_CAM5                    33005
#define ID_FILE_CAM6                    33006
#define ID_FILE_CAM7                    33007
#define ID_FILE_CAM8                    33008
#define ID_FILE_CAM9                    33009
#define ID_FILE_CAM10                   33010
#define ID_FILE_CAM11                   33011
#define ID_FILE_CAM12                   33012
#define ID_FILE_CAM13                   33013
#define ID_FILE_CAM14                   33014
#define ID_FILE_CAM15                   33015
#define ID_FILE_CAM16                   33016
#define ID_FILE_CAM17                   33017
#define ID_FILE_CAM18                   33018
#define ID_FILE_CAM19                   33019
#define ID_FILE_CAM20                   33020
#define ID_FILE_CAM21                   33021
#define ID_MBO_0                        33099
#define ID_MBO_1                        33100
#define ID_MBO_2                        33101
#define ID_MBO_3                        33102
#define ID_MBO_4                        33103
#define ID_MBO_5                        33104
#define ID_MBO_6                        33105
#define ID_MBO_7                        33106
#define ID_MBO_8                        33107
#define ID_MBO_9                        33108
#define ID_MBO_10                       33109

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        362
#define _APS_NEXT_COMMAND_VALUE         32944
#define _APS_NEXT_CONTROL_VALUE         1563
#define _APS_NEXT_SYMED_VALUE           106
#endif
#endif
